# -*- coding: utf-8 -*-
"""assesment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQw9VByfKDFkBI0QDRUYYjwqqerexQQO
"""

# WAP TO PRINT YOUR NAME,AGE,CITY IN ONE LINE

Name = "priyanshi"
age = 21
City = "Valsad"

print(f"Name:{Name}, age:{age}, city:{City}")

# TAKE USER INPUT FOR TWO NUMBERS AND PRINT THEIR SUM

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

sum = num1 + num2
print("Sum of two numbers is:", sum)

#WAP TO CONVERT TEMPRATURE FROM CELSIUS TO FERANHIT.

celsius = float(input("Enter temperature in Celsius: "))
fahrenheit = (celsius * 9/5) + 32
print("Temperature in Fahrenheit:", fahrenheit)

#STORE YOUR NAME IN VARIABLE AND PRINT IN UPPER CASE

name = "Priyanshi Patel"
print(name.upper())

# ASK THE USER FOR THEIR BRTH YEAR AND CALCULATE THEIR CURRENT AGE

from datetime import date

birth_year = int(input("Enter your birth year: "))
current_year = date.today().year

age = current_year - birth_year

print("Your current age is:", age)

# WAP TO SWAP TWO VARIABLES

a = 25
b = 87

a, b = b, a

print("After swapping:", a,b)

# CREATE A PROGRAM TO CALCULATE THE AREA OF A RECTANGLE FROM USER

length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

area = length * width

print("Area of the rectangle is:", area)

# WAP TO CHECK IF NUMBER IS POSITIVE OR NEGATIVE

num = int(input("Enter a number: "))

if num > 0:
    print("The number is Positive")
elif num < 0:
    print("The number is Negative")
else:
    print("The number is Zero")

# ASK FOR TWO NUMBER AND PRINT THEIR AVERAGE

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

average = (num1 + num2) / 2

print("Average of the two numbers is:", average)