# -*- coding: utf-8 -*-
"""assesment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114_ZFO0evUCDhJh_tNE9iqu_a_u3fBRo
"""

#1. calculate the reminder of the two number

num1 = int(input("enter number1:"))
num2 = int(input("enter number2:"))

reminder = num1 % num2

print("reminder is :",reminder)

#2. check if a number is even or odd

num = int(input("Enter number:"))

if num % 2 ==0:
    print("number is even")
else:
    print("number is odd")

#3. compare two number and print the large number

num1 = int(input("Enter the number1: "))
num2 = int(input("Enter the number2: "))

if num1 > num2:
    print("num1 is large")
else:
    print("num2 is large")

#4. WAP to calculate the square and cube of a number

num = int(input("Enter the number: "))

square = num ** 2
cube = num ** 3

print("square of",num,"is",square)
print("cube of",num,"is",cube )

# 5. check if two entered number are equal.

num1 = int(input("Enter number1: "))
num2 = int(input("Enter number2: "))

if num1 == num2:
    print("numbers are equal")
else:
    print("numbers are not equal")

#6. take two number and print true if both are positive else false

num1 = int(input("Enter number1:"))
num2 = int(input("Enter number2:"))

if num1>0 and num2>0:
  print("true")
else:
  print("false")

#7. WAP to convert float to integer

num = float(input("Enter number:"))
num_integer = int(num)

print("integer number:",num_integer)

#8. take a number asstring, convert to int, and multiply by 10

num_str = input("Enter number:")
num_int = int(num_str) * 10
print("number:",num_int)

#9. WAP that uses and & or operator to check multiple conditions
#AND operator
num1 = int(input("Enter number1:"))
num2 = int(input("Enter number2:"))

if num1>0 and num2>0:
  print("true")
else:
  print("false")

num1 = int(input("Enter number1:"))
num2 = int(input("Enter number2:"))

if num1>0 or num2>0:
  print("true")
else:
  print("false")

# divide two numbers and print the quotient and remainder seprately

num1 = int(input("Enter number1:"))
num2 = int(input("Enter number2:"))

quotient = num1 // num2
remainder = num1 % num2

print("quotient:",quotient)
print("remainder:",remainder)